In [1]:
import poolparty as pp

In [2]:
# pool.ops.mutagenize() applies mutagenize() to a marked region
with pp.Party():
    bg = pp.from_seq('FLANK<target>ACGT</target>FLANK')
    result = bg.ops.mutagenize('target', num_mutations=1, mark_changes=True, mode='sequential')
    df = result.generate_library(num_cycles=1)
df

,seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[3].state,pool[2].state,pool[1].state,pool[0].state,op[3]:replace_marker_content.state,op[2]:mutagenize.state,op[1]:fixed.state,op[0]:fixed.state,op[2]:mutagenize.key.positions,op[2]:mutagenize.key.wt_chars,op[2]:mutagenize.key.mut_chars
0,FLANKcCGTFLANK,FLANKcCGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,0,None,None,0,0,0,0,0,"(0,)","(A,)","(c,)"
1,FLANKgCGTFLANK,FLANKgCGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,1,None,None,0,0,1,0,0,"(0,)","(A,)","(g,)"
2,FLANKtCGTFLANK,FLANKtCGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,2,None,None,0,0,2,0,0,"(0,)","(A,)","(t,)"
3,FLANKAaGTFLANK,FLANKAaGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,3,None,None,0,0,3,0,0,"(1,)","(C,)","(a,)"
4,FLANKAgGTFLANK,FLANKAgGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,4,None,None,0,0,4,0,0,"(1,)","(C,)","(g,)"
5,FLANKAtGTFLANK,FLANKAtGTFLANK,None,None,FLANK<target>ACGT</target>FLANK,5,None,None,0,0,5,0,0,"(1,)","(C,)","(t,)"
6,FLANKACaTFLANK,FLANKACaTFLANK,None,None,FLANK<target>ACGT</target>FLANK,6,None,None,0,0,6,0,0,"(2,)","(G,)","(a,)"
7,FLANKACcTFLANK,FLANKACcTFLANK,None,None,FLANK<target>ACGT</target>FLANK,7,None,None,0,0,7,0,0,"(2,)","(G,)","(c,)"
8,FLANKACtTFLANK,FLANKACtTFLANK,None,None,FLANK<target>ACGT</target>FLANK,8,None,None,0,0,8,0,0,"(2,)","(G,)","(t,)"
9,FLANKACGaFLANK,FLANKACGaFLANK,None,None,FLANK<target>ACGT</target>FLANK,9,None,None,0,0,9,0,0,"(3,)","(T,)","(a,)"
10,FLANKACGcFLANK,FLANKACGcFLANK,None,None,FLANK<target>ACGT</target>FLANK,10,None,None,0,0,10,0,0,"(3,)","(T,)","(c,)"
11,FLANKACGgFLANK,FLANKACGgFLANK,None,None,FLANK<target>ACGT</target>FLANK,11,None,None,0,0,11,0,0,"(3,)","(T,)","(g,)"

In [3]:
# pool.ops.deletion_scan() applies deletion_scan() to a marked region
with pp.Party():
    bg = pp.from_seq('AAA<region>ACGTACGT</region>TTT')
    result = bg.ops.deletion_scan('region', deletion_length=2, mode='sequential')
    df = result.generate_library(num_cycles=1)
df

,seq,pool[5].seq,pool[4].seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[5].state,pool[4].state,pool[3].state,...,pool[0].state,op[5]:replace_marker_content.state,op[4]:replace_marker_content.state,op[3]:fixed.state,op[2]:marker_scan.state,op[1]:fixed.state,op[0]:fixed.state,op[2]:marker_scan.key.position,op[2]:marker_scan.key.strand,op[2]:marker_scan.key.marker_tag
0,AAA--GTACGTTTT,AAA--GTACGTTTT,None,--,None,None,AAA<region>ACGTACGT</region>TTT,0,None,0,...,0,0,0,0,0,0,0,0,+,<_del>AC</_del>
1,AAAA--TACGTTTT,AAAA--TACGTTTT,None,--,None,None,AAA<region>ACGTACGT</region>TTT,1,None,0,...,0,0,0,0,1,0,0,1,+,<_del>CG</_del>
2,AAAAC--ACGTTTT,AAAAC--ACGTTTT,None,--,None,None,AAA<region>ACGTACGT</region>TTT,2,None,0,...,0,0,0,0,2,0,0,2,+,<_del>GT</_del>
3,AAAACG--CGTTTT,AAAACG--CGTTTT,None,--,None,None,AAA<region>ACGTACGT</region>TTT,3,None,0,...,0,0,0,0,3,0,0,3,+,<_del>TA</_del>
4,AAAACGT--GTTTT,AAAACGT--GTTTT,None,--,None,None,AAA<region>ACGTACGT</region>TTT,4,None,0,...,0,0,0,0,4,0,0,4,+,<_del>AC</_del>
5,AAAACGTA--TTTT,AAAACGTA--TTTT,None,--,None,None,AAA<region>ACGTACGT</region>TTT,5,None,0,...,0,0,0,0,5,0,0,5,+,<_del>CG</_del>
6,AAAACGTAC--TTT,AAAACGTAC--TTT,None,--,None,None,AAA<region>ACGTACGT</region>TTT,6,None,0,...,0,0,0,0,6,0,0,6,+,<_del>GT</_del>

In [4]:
# pool.ops.insertion_scan() applies insertion_scan() to a marked region
with pp.Party():
    bg = pp.from_seq('AAA<region>ACGT</region>TTT')
    result = bg.ops.insertion_scan('region', 'XX', mode='sequential')
    df = result.generate_library(num_cycles=1)
df

,seq,pool[5].seq,pool[4].seq,pool[3].seq,pool[1].seq,pool[0].seq,pool[2].seq,pool[5].state,pool[4].state,pool[3].state,...,pool[2].state,op[5]:replace_marker_content.state,op[4]:replace_marker_content.state,op[3]:marker_scan.state,op[1]:fixed.state,op[0]:fixed.state,op[2]:fixed.state,op[3]:marker_scan.key.position,op[3]:marker_scan.key.strand,op[3]:marker_scan.key.marker_tag
0,AAAXXACGTTTT,AAAXXACGTTTT,None,None,None,AAA<region>ACGT</region>TTT,XX,0,None,None,...,0,0,0,0,0,0,0,0,+,<_ins/>
1,AAAAXXCGTTTT,AAAAXXCGTTTT,None,None,None,AAA<region>ACGT</region>TTT,XX,1,None,None,...,0,0,0,1,0,0,0,1,+,<_ins/>
2,AAAACXXGTTTT,AAAACXXGTTTT,None,None,None,AAA<region>ACGT</region>TTT,XX,2,None,None,...,0,0,0,2,0,0,0,2,+,<_ins/>
3,AAAACGXXTTTT,AAAACGXXTTTT,None,None,None,AAA<region>ACGT</region>TTT,XX,3,None,None,...,0,0,0,3,0,0,0,3,+,<_ins/>
4,AAAACGTXXTTT,AAAACGTXXTTT,None,None,None,AAA<region>ACGT</region>TTT,XX,4,None,None,...,0,0,0,4,0,0,0,4,+,<_ins/>

In [5]:
# pool.ops.replacement_scan() applies replacement_scan() to a marked region
with pp.Party():
    bg = pp.from_seq('AAA<region>ACGTACGT</region>TTT')
    result = bg.ops.replacement_scan('region', 'NN', mark_changes=True, mode='sequential')
    df = result.generate_library(num_cycles=1)
df

,seq,pool[6].seq,pool[5].seq,pool[3].seq,pool[2].seq,pool[4].seq,pool[1].seq,pool[0].seq,pool[6].state,pool[5].state,...,op[6]:replace_marker_content.state,op[5]:replace_marker_content.state,op[3]:fixed.state,op[2]:fixed.state,op[4]:marker_scan.state,op[1]:fixed.state,op[0]:fixed.state,op[4]:marker_scan.key.position,op[4]:marker_scan.key.strand,op[4]:marker_scan.key.marker_tag
0,AAAnnGTACGTTTT,AAAnnGTACGTTTT,None,None,NN,None,None,AAA<region>ACGTACGT</region>TTT,0,None,...,0,0,0,0,0,0,0,0,+,<_rep>AC</_rep>
1,AAAAnnTACGTTTT,AAAAnnTACGTTTT,None,None,NN,None,None,AAA<region>ACGTACGT</region>TTT,1,None,...,0,0,0,0,1,0,0,1,+,<_rep>CG</_rep>
2,AAAACnnACGTTTT,AAAACnnACGTTTT,None,None,NN,None,None,AAA<region>ACGTACGT</region>TTT,2,None,...,0,0,0,0,2,0,0,2,+,<_rep>GT</_rep>
3,AAAACGnnCGTTTT,AAAACGnnCGTTTT,None,None,NN,None,None,AAA<region>ACGTACGT</region>TTT,3,None,...,0,0,0,0,3,0,0,3,+,<_rep>TA</_rep>
4,AAAACGTnnGTTTT,AAAACGTnnGTTTT,None,None,NN,None,None,AAA<region>ACGTACGT</region>TTT,4,None,...,0,0,0,0,4,0,0,4,+,<_rep>AC</_rep>
5,AAAACGTAnnTTTT,AAAACGTAnnTTTT,None,None,NN,None,None,AAA<region>ACGTACGT</region>TTT,5,None,...,0,0,0,0,5,0,0,5,+,<_rep>CG</_rep>
6,AAAACGTACnnTTT,AAAACGTACnnTTT,None,None,NN,None,None,AAA<region>ACGTACGT</region>TTT,6,None,...,0,0,0,0,6,0,0,6,+,<_rep>GT</_rep>

In [6]:
# pool.ops.mutagenize_scan() applies mutagenize_scan() to a marked region
with pp.Party():
    bg = pp.from_seq('AAA<region>ACGTACGT</region>TTT')
    result = bg.ops.mutagenize_scan('region', mutagenize_length=4, num_mutations=1, mode='sequential')
    df = result.generate_library(num_cycles=1, seed=42)
df

,seq,pool[6].seq,pool[5].seq,pool[4].seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[6].state,pool[5].state,...,op[3]:fixed.state,op[2]:marker_scan.state,op[1]:fixed.state,op[0]:fixed.state,op[4]:mutagenize.key.positions,op[4]:mutagenize.key.wt_chars,op[4]:mutagenize.key.mut_chars,op[2]:marker_scan.key.position,op[2]:marker_scan.key.strand,op[2]:marker_scan.key.marker_tag
0,AAATCGTACGTTTT,AAATCGTACGTTTT,None,None,None,None,None,AAA<region>ACGTACGT</region>TTT,0,None,...,0,0,0,0,"(0,)","(A,)","(T,)",0,+,<_mut>ACGT</_mut>
1,AAAACGCACGTTTT,AAAACGCACGTTTT,None,None,None,None,None,AAA<region>ACGTACGT</region>TTT,1,None,...,0,1,0,0,"(2,)","(T,)","(C,)",1,+,<_mut>CGTA</_mut>
2,AAAACGGACGTTTT,AAAACGGACGTTTT,None,None,None,None,None,AAA<region>ACGTACGT</region>TTT,2,None,...,0,2,0,0,"(1,)","(T,)","(G,)",2,+,<_mut>GTAC</_mut>
3,AAAACGGACGTTTT,AAAACGGACGTTTT,None,None,None,None,None,AAA<region>ACGTACGT</region>TTT,3,None,...,0,3,0,0,"(0,)","(T,)","(G,)",3,+,<_mut>TACG</_mut>
4,AAAACGTCCGTTTT,AAAACGTCCGTTTT,None,None,None,None,None,AAA<region>ACGTACGT</region>TTT,4,None,...,0,4,0,0,"(0,)","(A,)","(C,)",4,+,<_mut>ACGT</_mut>

In [7]:
# pool.ops.shuffle_scan() applies shuffle_scan() to a marked region
with pp.Party():
    bg = pp.from_seq('AAA<region>ACGTACGT</region>TTT')
    result = bg.ops.shuffle_scan('region', shuffle_length=4, mark_changes=True, mode='sequential')
    df = result.generate_library(num_cycles=1, seed=42)
df

,seq,pool[7].seq,pool[6].seq,pool[5].seq,pool[4].seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[7].state,...,op[5]:fixed.state,op[4]:shuffle_seq.state,op[3]:fixed.state,op[2]:marker_scan.state,op[1]:fixed.state,op[0]:fixed.state,op[4]:shuffle_seq.key.permutation,op[2]:marker_scan.key.position,op[2]:marker_scan.key.strand,op[2]:marker_scan.key.marker_tag
0,AAAtgcaACGTTTT,AAAtgcaACGTTTT,None,None,None,None,None,None,AAA<region>ACGTACGT</region>TTT,0,...,0,0,0,0,0,0,"(3, 2, 1, 0)",0,+,<_shuf>ACGT</_shuf>
1,AAAAatcgCGTTTT,AAAAatcgCGTTTT,None,None,None,None,None,None,AAA<region>ACGTACGT</region>TTT,1,...,0,0,0,1,0,0,"(2, 3, 1, 0)",1,+,<_shuf>CGTA</_shuf>
2,AAAACgcatGTTTT,AAAACgcatGTTTT,None,None,None,None,None,None,AAA<region>ACGTACGT</region>TTT,2,...,0,0,0,2,0,0,"(0, 3, 2, 1)",2,+,<_shuf>GTAC</_shuf>
3,AAAACGcgtaTTTT,AAAACGcgtaTTTT,None,None,None,None,None,None,AAA<region>ACGTACGT</region>TTT,3,...,0,0,0,3,0,0,"(2, 3, 0, 1)",3,+,<_shuf>TACG</_shuf>
4,AAAACGTgtacTTT,AAAACGTgtacTTT,None,None,None,None,None,None,AAA<region>ACGTACGT</region>TTT,4,...,0,0,0,4,0,0,"(2, 3, 0, 1)",4,+,<_shuf>ACGT</_shuf>

In [8]:
# pool.ops.shuffle_seq() shuffles the content of a marked region
with pp.Party():
    bg = pp.from_seq('AAA<region>ACGT</region>TTT')
    result = bg.ops.shuffle_seq('region')
    df = result.generate_library(num_cycles=3, seed=42)
df

,seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[3].state,pool[2].state,pool[1].state,pool[0].state,op[3]:replace_marker_content.state,op[2]:shuffle_seq.state,op[1]:fixed.state,op[0]:fixed.state,op[2]:shuffle_seq.key.permutation
0,AAATGCATTT,AAATGCATTT,None,None,AAA<region>ACGT</region>TTT,0,None,None,0,0,0,0,0,"(3, 2, 1, 0)"
1,AAATGACTTT,AAATGACTTT,None,None,AAA<region>ACGT</region>TTT,0,None,None,0,0,0,0,0,"(2, 3, 1, 0)"
2,AAAATGCTTT,AAAATGCTTT,None,None,AAA<region>ACGT</region>TTT,0,None,None,0,0,0,0,0,"(0, 3, 2, 1)"

In [9]:
# pool.ops.from_iupac_motif() replaces marker with IUPAC-generated sequences
with pp.Party():
    bg = pp.from_seq('AAA<insert/>TTT')
    result = bg.ops.from_iupac_motif('insert', 'RN', mode='sequential')
    df = result.generate_library(num_cycles=1)
df

,seq,pool[2].seq,pool[0].seq,pool[1].seq,pool[2].state,pool[0].state,pool[1].state,op[2]:replace_marker_content.state,op[0]:fixed.state,op[1]:from_iupac_motif.state,op[1]:from_iupac_motif.key.iupac_state
0,AAAAATTT,AAAAATTT,AAA<insert/>TTT,AA,0,0,0,0,0,0,0
1,AAAACTTT,AAAACTTT,AAA<insert/>TTT,AC,1,0,1,0,0,1,1
2,AAAAGTTT,AAAAGTTT,AAA<insert/>TTT,AG,2,0,2,0,0,2,2
3,AAAATTTT,AAAATTTT,AAA<insert/>TTT,AT,3,0,3,0,0,3,3
4,AAAGATTT,AAAGATTT,AAA<insert/>TTT,GA,4,0,4,0,0,4,4
5,AAAGCTTT,AAAGCTTT,AAA<insert/>TTT,GC,5,0,5,0,0,5,5
6,AAAGGTTT,AAAGGTTT,AAA<insert/>TTT,GG,6,0,6,0,0,6,6
7,AAAGTTTT,AAAGTTTT,AAA<insert/>TTT,GT,7,0,7,0,0,7,7

In [10]:
# pool.ops.get_kmers() replaces marker with k-mer sequences
with pp.Party():
    bg = pp.from_seq('AAA<insert/>TTT')
    result = bg.ops.get_kmers('insert', length=2, mode='sequential')
    df = result.generate_library(num_cycles=1)
df

,seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[2].state,pool[1].state,pool[0].state,op[2]:replace_marker_content.state,op[1]:get_kmers.state,op[0]:fixed.state,op[1]:get_kmers.key.kmer_index
0,AAAAATTT,AAAAATTT,AA,AAA<insert/>TTT,0,0,0,0,0,0,0
1,AAAACTTT,AAAACTTT,AC,AAA<insert/>TTT,1,1,0,0,1,0,1
2,AAAAGTTT,AAAAGTTT,AG,AAA<insert/>TTT,2,2,0,0,2,0,2
3,AAAATTTT,AAAATTTT,AT,AAA<insert/>TTT,3,3,0,0,3,0,3
4,AAACATTT,AAACATTT,CA,AAA<insert/>TTT,4,4,0,0,4,0,4
5,AAACCTTT,AAACCTTT,CC,AAA<insert/>TTT,5,5,0,0,5,0,5
6,AAACGTTT,AAACGTTT,CG,AAA<insert/>TTT,6,6,0,0,6,0,6
7,AAACTTTT,AAACTTTT,CT,AAA<insert/>TTT,7,7,0,0,7,0,7
8,AAAGATTT,AAAGATTT,GA,AAA<insert/>TTT,8,8,0,0,8,0,8
9,AAAGCTTT,AAAGCTTT,GC,AAA<insert/>TTT,9,9,0,0,9,0,9
10,AAAGGTTT,AAAGGTTT,GG,AAA<insert/>TTT,10,10,0,0,10,0,10
11,AAAGTTTT,AAAGTTTT,GT,AAA<insert/>TTT,11,11,0,0,11,0,11
12,AAATATTT,AAATATTT,TA,AAA<insert/>TTT,12,12,0,0,12,0,12
13,AAATCTTT,AAATCTTT,TC,AAA<insert/>TTT,13,13,0,0,13,0,13
14,AAATGTTT,AAATGTTT,TG,AAA<insert/>TTT,14,14,0,0,14,0,14
15,AAATTTTT,AAATTTTT,TT,AAA<insert/>TTT,15,15,0,0,15,0,15

In [11]:
# pool.ops.from_prob_motif() replaces marker with probability-sampled sequences
import pandas as pd
prob_df = pd.DataFrame({'A': [0.5, 0.0], 'C': [0.5, 0.0], 'G': [0.0, 0.5], 'T': [0.0, 0.5]})
with pp.Party():
    bg = pp.from_seq('AAA<insert/>TTT')
    result = bg.ops.from_prob_motif('insert', prob_df, mode='random')
    df = result.generate_library(num_cycles=3, seed=42)
df

,seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[2].state,pool[1].state,pool[0].state,op[2]:replace_marker_content.state,op[1]:from_prob_motif.state,op[0]:fixed.state,op[1]:from_prob_motif.key.prob_state
0,AAACGTTT,AAACGTTT,CG,AAA<insert/>TTT,0,0,0,0,0,0,"[1, 2]"
1,AAACTTTT,AAACTTTT,CT,AAA<insert/>TTT,0,0,0,0,0,0,"[1, 3]"
2,AAAATTTT,AAAATTTT,AT,AAA<insert/>TTT,0,0,0,0,0,0,"[0, 3]"

In [12]:
# pool.ops.apply_at_marker() applies a custom transform to a marked region
with pp.Party():
    bg = pp.from_seq('AAA<target>ACGT</target>TTT')
    result = bg.ops.apply_at_marker('target', lambda p: pp.mutagenize(p, num_mutations=1))
    df = result.generate_library(num_cycles=1, seed=42)
df

,seq,pool[3].seq,pool[2].seq,pool[1].seq,pool[0].seq,pool[3].state,pool[2].state,pool[1].state,pool[0].state,op[3]:replace_marker_content.state,op[2]:mutagenize.state,op[1]:fixed.state,op[0]:fixed.state,op[2]:mutagenize.key.positions,op[2]:mutagenize.key.wt_chars,op[2]:mutagenize.key.mut_chars
0,AAATCGTTTT,AAATCGTTTT,None,None,AAA<target>ACGT</target>TTT,0,None,None,0,0,0,0,0,"(0,)","(A,)","(T,)"