In [1]:
import poolparty as pp
import statecounter as sc
pp.init()

Party(outputs=[])

In [2]:
# Create two pools via ordered_product to show default behavior
A = pp.from_seqs(['a1', 'a2'], name='A')
B = pp.from_seqs(['b1', 'b2', 'b3'], name='B')
C = pp.join([A, B], name='AB')
C.generate_library(num_cycles=1)

,seq,AB.seq,B.seq,A.seq,AB.state,B.state,A.state,op[2]:fixed.state,op[1]:from_seqs.state,op[0]:from_seqs.state,op[1]:from_seqs.key.seq_name,op[1]:from_seqs.key.seq_index,op[0]:from_seqs.key.seq_name,op[0]:from_seqs.key.seq_index
0,a2b2,a2b2,b2,a2,0,0,0,0,0,0,seq_1,1,seq_1,1

In [3]:
# Default: 'first_counter_fastest' - lower ID counters (A) cycle fastest
sc.get_product_order_mode()

'first_counter_fastest'

In [4]:
# Switch to 'first_counter_slowest' mode using pp.set_default
pp.set_default('iter_order', 'first_counter_slowest')
sc.get_product_order_mode()

'first_counter_slowest'

In [5]:
# Now A (first created) will cycle slowest, B cycles fastest
pp.init()
A = pp.from_seqs(['a1', 'a2'], name='A')
B = pp.from_seqs(['b1', 'b2', 'b3'], name='B')
C = pp.join([A, B], name='AB')
C.generate_library(num_cycles=1)

,seq,AB.seq,A.seq,B.seq,AB.state,A.state,B.state,op[2]:fixed.state,op[0]:from_seqs.state,op[1]:from_seqs.state,op[0]:from_seqs.key.seq_name,op[0]:from_seqs.key.seq_index,op[1]:from_seqs.key.seq_name,op[1]:from_seqs.key.seq_index
0,a2b2,a2b2,a2,b2,0,0,0,0,0,0,seq_1,1,seq_1,1

In [6]:
# Reset to default behavior
pp.set_default('iter_order', 'first_counter_fastest')
sc.get_product_order_mode()

'first_counter_fastest'